baseurl = ""
languageCode = "en-us"
title = "raphael & impress"
theme = "autophugo"
#googleAnalytics = ""
disableKinds = ["taxonomy", "term"]
#[taxonomies]
#    tag = "tags"
#    category = "categories"

[Author]
    name = "scillidan"
    email = "scillidan@yandex.com"

[params]
    # Meta
    description = ""
    keywords = "oil painting, gallery, pre-raphaelite, impressionist"
    #msvalidate = ""
    #googlesiteverification = ""
    #thumb_width = 480
    thumb_quality = 60
    #full_width = 960
    #full_quality = 90
    column_count = 4
    breadcrumb_use_title = true
    filename_as_phototitle = true
    images_downloadable = false
    images_downloadable_use_orig = true
    #taxonomies_links = false

    [[params.header.links]]
    name = ""
    url = "#footer"
    icon = "iconfont a-269-info"

    # Footer panel

    [params.footer.paragraph]
    headline = ""
    text = ""

    [params.footer.social]
    headline = ""

    [[params.footer.social.links]]
    label = ""
    url = ""
    icon = ""

    [params.footer.contact]
    hide = true
    # realEmail = "example@example.org"
    # headline = "Get in touch"
    # buttonText = "Send"
    # resetText = "Reset"

    # 'warning' defines error messages for invalid inputs
    [params.footer.contact.name]
    text = "Name *"
    warning = "Please, enter your name"

    [params.footer.contact.email]
    text = "Email *"
    warning = "Please, enter your email."

    [params.footer.contact.message]
    text = "Message *"
    warning = "Please, enter your message"

    # Copyright
    [params.footer.copyright]
    name = "scillidan"